version: '3.8'

services:
  seanime:
    build:
      context: .
      dockerfile: Dockerfile
    image: seanime:latest
    container_name: seanime
    working_dir: /app
    volumes:
      - /aeternae/theater/anime/completed/:/media/anime
      - /aeternae/library/manga/completed/:/media/manga
      - /aeternae/functional/torrents/torrent_files/animechanical/:/downloads
      - ./data/qbittorrent:/app/qbittorrent-profile
      - ./data/seanime:/app/data
      - ./resolv.conf:/etc/resolv.conf
      # qBittorrent-nox credentials: admin/qbpassword, Web UI: http://localhost:912
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    environment:
      - TZ=UTC
    restart: unless-stopped
    # Note: Ports cannot be published directly in this mode. To access the web UI, publish ports via Gluetun or use a VPN client on your host.

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    network_mode: "bridge"
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=MULLVAD
      - OPENVPN_USER=5254230649909803
      - OPENVPN_PASSWORD=x
      - SERVER_COUNTRIES=Sweden
      - TZ=UTC
      - DOT_PROVIDERS=cloudflare
      - EXTRA_SUBNETS=10.147.20.0/24
    volumes:
      - ./vpn:/gluetun/custom
      # Place your .ovpn config file and certs in ./vpn if you want to use custom config
    ports:
      - "43211:43211"   # Seanime Web UI
      - "912:912"       # qBittorrent Web UI (now inside Seanime container)
      - "6881:6881"     # BitTorrent protocol
      - "6881:6881/udp"
    restart: unless-stopped
